[options]
addons_path = /mnt/extra-addons
admin_passwd = $pbkdf2-sha512$600000$J8QYQ8g5h7B2jjGmdO4dww$fJTDX86iWI1vWhqViOW0Fh7pr/uFd3iUkauaqYGXRVUWAJ777ZC5avtVPkiZiIlIDLKErDU8cLnYssLJ2CCX9A
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
http_interface = 0.0.0.0

[colors]
pid = never
loglevel = auto
session_id = never
http_request_line = auto
http_response_body = auto
perf = auto
cursor_mode = auto
sql = auto

